# Generated by Django 4.1.7 on 2023-03-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitcontrolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Councilor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coun_img', models.ImageField(upload_to='pics')),
                ('coun_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_ph', models.CharField(max_length=12)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('coun_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitcontrolapp.councilor')),
            ],
        ),
    ]
